[workspace]
members = ["common", "pyext", "cmd"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.80"
homepage = "https://github.com/hugues-aff/import-parser-rs"
documentation = "https://github.com/hugues-aff/import-parser-rs"
repository = "https://github.com/hugues-aff/import-parser-rs"
authors = ["Hugues Bruant <hugues.bruant@gmail.com>"]
license = "MIT"

[workspace.dependencies]
common = { path = "common" }
cmd = { path = "cmd" }
pyext = { path = "pyext" }

pyo3 = "0.22.5"
walkdir = "2.5"
dashmap = "6.1"
ruff_python_parser = { git = "https://github.com/astral-sh/ruff.git", tag = "0.7.1" }
ruff_python_ast = { git = "https://github.com/astral-sh/ruff.git", tag = "0.7.1" }
ruff_text_size = { git = "https://github.com/astral-sh/ruff.git", tag = "0.7.1" }

[profile.release]
debug = 1
